name: Build and Push to dist Branch

on:
  push:
    branches:
      - main   # change this to your source branch

permissions:
  contents: write

jobs:
  deploy-dist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0          # needed to detect or create branches

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'     # upgraded from 16 to 20

      - name: Verify Node.js and NPM versions
        run: |
          echo "Node: $(node -v)"
          echo "NPM:  $(npm -v)"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Switch to dist branch (or create it)
        run: |
          if git rev-parse --verify origin/dist; then
            git checkout dist
          else
            git checkout --orphan dist
          fi

      - name: Clean old contents
        run: |
          # remove everything except .git
          git rm -rf . >/dev/null 2>&1 || true

      - name: Copy build output
        run: |
          cp -r dist/* .
          # if you have hidden files in dist, uncomment:
          # cp -r dist/.[!.]* .

      - name: Commit & push to dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          git commit -m "chore: deploy build to dist branch" || echo "No changes to commit"
          git push --force origin dist
